service: LevertonCustomSkill
provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1

functions:
  leverton-custom-skill:
    handler: index.handler
    name: leverton-custom-skill
    runtime: nodejs8.10
    timeout: 300
    events:
      - http:
          method: POST
          path: skill
          cors: true
    environment:
      LEVERTON_AUTH_TOKEN: bW1pdGNoZWxsQGJveC5jb206NTQyRHZTWm9PRmoxVTladCE=
      LEVERTON_PROJECT_ID: 330
      DEFAULT_COLLECTION_ID: 65579
