service: RossumCustomSkill
provider:
  name: aws
  runtime: nodejs8.10  
  region: us-east-1

functions:
  index:
    handler: index.handler
    name: skill
    runtime: nodejs8.10
    timeout: 30
    events:
      - http:
          method: POST
          path: skill
          cors: true
    environment:
      ROSSUM_SECRET_KEY: YOUR_ROSSUM_SECRET_KEY
